name: yuzu-android-build2

on:
  workflow_dispatch:

jobs:
  build-yuzu:
    runs-on: ubuntu-latest

    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: "temurin"

      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            ~/.ccache
          key: ${{ runner.os }}-android-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-android-

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ccache apksigner glslang-dev glslang-tools

      - name: Build
        run: ./.ci/scripts/android/build.sh

      - name: Copy artifacts
        run: ./.ci/scripts/android/upload.sh

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: android
          path: artifacts/*.apk

